-- 测试下载速度
-- EXEC sph_TestSpeed
-- EXEC sph_TestSpeed 5, 10
-- EXEC sph_Check
-- EXEC sph_Correct
-- EXEC sph_UpdateCorp
-- EXEC sph_CreateViews
SELECT TOP 100 * FROM CORP

SELECT IMG_Accurate, COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Type = 'T' GROUP BY IMG_Accurate

SELECT COUNT(*) AS CORP_Count FROM CORP
-- SELECT COUNT(*) FROM CORP WHERE CORP_Page IS NULL
-- SELECT CORP_Count, CORP_TYPE, COUNT(*) AS PAGE_Count FROM (SELECT CORP_Page, CORP_Type, COUNT(*) AS CORP_Count FROM CORP GROUP BY CORP_Page, CORP_Type) T GROUP BY CORP_Count, CORP_Type
-- SELECT CORP_Page, CORP_Type, COUNT(*) AS CORP_Count FROM CORP GROUP BY CORP_Page, CORP_Type HAVING COUNT(*) <> 55 AND CORP_Page <> 0
SELECT CORP_Status, CORP_Type, COUNT(*) AS CORP_Count FROM CORP WHERE CORP_Page > 0 GROUP BY CORP_Status, Corp_Type
-- SELECT COUNT(*) AS CORP_Count FROM (SELECT DISTINCT INFO_CorpID FROM INFO) T
-- SELECT COUNT(DISTINCT INFO_CorpID) AS CORP_Count FROM INFO
SELECT INFO_Status, COUNT(*) AS INFO_Count FROM INFO GROUP BY INFO_Status
SELECT IMG_Status, COUNT(*) AS IMG_Count FROM IMG GROUP BY IMG_Status
SELECT PAGE_Status, PAGE_Type, COUNT(*) AS PAGE_Count FROM PAGE GROUP BY PAGE_Status, PAGE_Type
SELECT COUNT(*) FROM CORP WHERE CORP_Status = 'I' AND CORP_ID IN (SELECT INFO_CorpID FROM INFO)

SELECT COUNT(*) AS INFO_Count, INFO_CorpID FROM INFO, CORP WHERE INFO_CorpID = CORP_ID AND CORP_Type = 'S' GROUP BY INFO_CorpID HAVING COUNT(*) <> 12
SELECT COUNT(*) AS INFO_Count, INFO_CorpID FROM INFO, CORP WHERE INFO_CorpID = CORP_ID AND CORP_Type = 'T' GROUP BY INFO_CorpID HAVING COUNT(*) <> 11
SELECT COUNT(*) AS CORP_Count FROM (SELECT COUNT(*) AS INFO_Count, INFO_CorpID FROM INFO, CORP WHERE INFO_CorpID = CORP_ID AND CORP_Type = 'S' GROUP BY INFO_CorpID HAVING COUNT(*) = 12) T
SELECT COUNT(*) AS CORP_Count FROM (SELECT COUNT(*) AS INFO_Count, INFO_CorpID FROM INFO, CORP WHERE INFO_CorpID = CORP_ID AND CORP_Type = 'T' GROUP BY INFO_CorpID HAVING COUNT(*) = 11) T
SELECT COUNT(*) AS INFO_Count FROM (SELECT COUNT(*) AS INFO_Count, INFO_CorpID FROM INFO GROUP BY INFO_CorpID) T
SELECT CORP_Status, CORP_Type, COUNT(*) AS CORP_Count FROM CORP GROUP BY CORP_Status, Corp_Type

SELECT COUNT(*) AS CORP_Count FROM CORP WHERE CORP_Page > 0 AND CORP_Scope IS NULL
SELECT COUNT(*) AS CORP_Count FROM CORP WHERE CORP_Page > 0 AND NOT EXISTS (SELECT INFO_CorpID FROM INFO WHERE INFO_CorpID = CORP_ID)
SELECT COUNT(*) AS CORP_Count FROM CORP WHERE NOT EXISTS (SELECT INFO_CorpID FROM INFO WHERE INFO_CorpID = CORP_ID)
SELECT TOP 20 * FROM CORP WHERE CORP_Page > 0 AND NOT EXISTS (SELECT INFO_CorpID FROM INFO WHERE INFO_CorpID = CORP_ID)
SELECT TOP 20 * FROM CORP WHERE CORP_Page = 0

-- UPDATE PAGE SET PAGE_Status = 'D' WHERE PAGE_ID IN (SELECT CORP_Page FROM CORP WHERE CORP_Type = 'S' GROUP BY CORP_Page HAVING COUNT(*) <> 55)
-- UPDATE PAGE SET PAGE_Status = 'D' WHERE PAGE_ID IN (SELECT CORP_Page FROM CORP WHERE CORP_Type = 'T' GROUP BY CORP_Page HAVING COUNT(*) <> 55)
SELECT CORP_Page, CORP_Type, COUNT(*) AS CORP_Count FROM CORP GROUP BY CORP_Page, CORP_Type HAVING COUNT(*) <> 55 ORDER BY CORP_Page ASC
SELECT CORP_Count, CORP_Type, COUNT(*) AS PAGE_Count FROM (SELECT CORP_Page, CORP_Type, COUNT(*) AS CORP_Count FROM CORP GROUP BY CORP_Page, CORP_Type) T GROUP BY CORP_Count, CORP_Type

SELECT COUNT(*) AS IMG_Count,MIN(IMG_Idx) AS IMG_Min, MAX(IMG_Idx) AS IMG_Max, MAX(LEN(IMG_Code)) AS Code_Max FROM IMG
SELECT COUNT(*), IMG_Idx AS IMG_Count FROM IMG GROUP BY IMG_Idx HAVING COUNT(*) > 1
SELECT COUNT(*) AS INFO_Count FROM INFO WHERE NOT EXISTS (SELECT IMG_Code FROM IMG WHERE IMG_Code = INFO_Code)

SELECT IMG_Status, COUNT(*) AS IMG_Count FROM IMG GROUP BY IMG_Status
SELECT IMG_Type, COUNT(*) AS IMG_Count FROM IMG GROUP BY IMG_Type
SELECT TYP_Code, TYP_NAME, MAX(LEN(IMG_Text)) AS TEXT_LEN FROM IMG, TYP WHERE IMG_Type = TYP_Code GROUP BY TYP_Code, TYP_NAME, TYP_Idx ORDER BY TYP_Idx ASC
SELECT * FROM (SELECT '0' AS IMG_Accurate, COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Accurate = 0 UNION SELECT '1-99' AS IMG_Accurate, COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Accurate > 0 AND IMG_Accurate < 100 UNION SELECT '100' AS IMG_Accurate, COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Accurate = 100 UNION SELECT '1000' AS IMG_Accurate, COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Accurate = 1000) T
SELECT * FROM IMG WHERE IMG_Accurate = 1000 AND IMG_Type = 'CD2'
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Accurate > 0
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Accurate = 0
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Status = 'S' AND IMG_Text IS NOT NULL
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Status = 'C' AND IMG_Text IS NULL
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Status = 'C' AND IMG_Accurate > 0
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Status = 'C'
SELECT COUNT(*) AS IMG_Count FROM IMG WHERE IMG_Status <> 'D' AND IMG_Text IS NOT NULL
-- UPDATE IMG SET IMG_Status = 'D' WHERE IMG_Status = 'S' AND IMG_Text IS NULL
-- UPDATE IMG SET IMG_Status = 'C' WHERE IMG_Status = 'S' AND IMG_Text IS NOT NULL

-- 压缩数据文件
BACKUP LOG Sylla WITH TRUNCATE_ONLY
DBCC Shrinkfile(Sylla_Log)

-- 修改IMG表
-- ALTER TABLE IMG DROP COLUMN IMG_Idx
-- ALTER TABLE IMG ADD IMG_Idx int not null IDENTITY
-- ALTER TABLE IMG DROP COLUMN IMG_Body
-- ALTER TABLE IMG ADD IMG_Type nvarchar(6)
-- UPDATE IMG SET IMG_Type = (SELECT MIN(INFO_Type) FROM INFO WHERE INFO_Code = IMG_Code)

-- 解决死锁问题
-- ALTER DATABASE Sylla SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE
/*
DROP INDEX [IIMG_IMG_Code] ON [dbo].[IMG]
CREATE NONCLUSTERED INDEX [IIMG_IMG_Code] ON [dbo].[IMG]
(
    [IIMG_IMG_Code] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
*/

-- select * from master.dbo.sysprocesses b where hostname = 'hsun'
-- select * from sys.dm_exec_connections where session_id = '54'
-- select * from sys.dm_exec_sessions where session_id = '54'

SELECT * FROM CORP WHERE CORP_ID = 9996778
SELECT * FROM INFO WHERE INFO_CorpID = 9996778
SELECT * FROM IMG WHERE IMG_Code IN (SELECT INFO_CODE FROM INFO WHERE INFO_CorpID = 9996778)
EXEC sp_lock

-- Sylla.T1 心理访谈
SELECT COUNT(*) FROM T1 WHERE Name LIKE '\[TLF\]08.%' ESCAPE '\'
SELECT COUNT(*) FROM T1
SELECT '20' + SUBSTRING(Name, 6, 2), COUNT(*) FROM T1 GROUP BY SUBSTRING(Name, 6, 2)
SELECT * FROM T1

-- test.*
SELECT * FROM T1 WHERE NAME COLLATE Chinese_PRC_CS_AS_WS LIKE N'%，%'
SELECT T1.*, T2.* FROM T1 FULL OUTER JOIN T2 ON T1.ID = T2.ID WHERE T1.ID IS NULL OR T2.ID IS NULL
*/